In [8]:
import torch
a = torch.rand(
    (5, 2, 2)
)
a

tensor([[[0.1247, 0.3411],
         [0.5039, 0.7099]],

        [[0.2472, 0.6066],
         [0.6769, 0.7741]],

        [[0.8046, 0.2997],
         [0.8716, 0.6732]],

        [[0.5652, 0.0184],
         [0.4001, 0.7935]],

        [[0.4406, 0.3109],
         [0.0145, 0.1380]]])

In [15]:
b = a.view(-1, 2)
c = b.view(a.shape)
b

tensor([[0.1247, 0.3411],
        [0.5039, 0.7099],
        [0.2472, 0.6066],
        [0.6769, 0.7741],
        [0.8046, 0.2997],
        [0.8716, 0.6732],
        [0.5652, 0.0184],
        [0.4001, 0.7935],
        [0.4406, 0.3109],
        [0.0145, 0.1380]])

In [14]:
c

tensor([[[0.1247, 0.3411],
         [0.5039, 0.7099]],

        [[0.2472, 0.6066],
         [0.6769, 0.7741]],

        [[0.8046, 0.2997],
         [0.8716, 0.6732]],

        [[0.5652, 0.0184],
         [0.4001, 0.7935]],

        [[0.4406, 0.3109],
         [0.0145, 0.1380]]])

In [2]:
dir = "/root/data/hyun_fp_data/hsqc_ms_pairs/val/HSQC_plain_imgs_toghter"
import torch
img = torch.load(dir+"/8.pt")

from matplotlib import pyplot as plt
plt.imshow(img[0], interpolation='nearest', cmap='gray')
plt.figure()
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: '/root/data/hyun_fp_data/hsqc_ms_pairs/val/HSQC_plain_imgs_toghter/8.pt'